update booking function
Blucas0707/taipei-day-trip-website pull request #12
Opened 2021-05-18 11:55 UTC by Blucas0707

林侑群：
1. Complete booking api
2. Complete booking page design

test url:
1. http://52.15.194.100:3000/

2021-05-18 19:55 UTC, cwpeng requested changes
點擊預定行程之後，預定行程的頁面第一時間點會顯示不出內容，要重新整理才能看到新的預訂內容。你的前端程式沒有確保預定行程後端運作完成才跳轉到 /booking 是個問題，請修正哦 ~

2021-05-19 03:31 UTC, Blucas0707 commented
發現確實是有時候get user info跟get booking api 同步執行，user api 跑得比較慢時，導致js user data fail=>會random 卡住
已修正get user info 完後, 才去執行get booking api.

2021-05-19 08:34 UTC, cwpeng requested changes
我去更改預定不同的景點行程時，預定頁面中的圖片都不會變化哦 ~

2021-05-19 08:50 UTC, Blucas0707 commented
已修正！謝謝老師提醒！

2021-05-19 14:23 UTC, cwpeng approved these changes
好哦，這樣就可以了 :)

2021-05-19 17:52 UTC, merged